apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus-ds
    jsonData:
      httpMethod: GET
      manageAlerts: false
      prometheusType: Prometheus

  - name: PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    uid: postgres-ds
    database: users_db
    user: user
    secureJsonData:
      password: password
    jsonData:
      database: users_db
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false
